import Head from 'next/head'
import { signIn } from 'next-auth/react'
import styled from 'styled-components'
import { useState } from 'react'
import Image from 'next/image'

export default function Login() {
  const [loading, setLoading] = useState(false)
  const handleSignIn = () => {
    if (loading) {
      return
    }
    setLoading(true)
    signIn('github').catch(() => setLoading(false))
  }
  return (
    <Container>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LoginCard>
        <Image width={100} height={100} src='/favicon.ico' alt='logo' />
        <LoginHead>Login to QuestionFlow</LoginHead>
        <LoginButton disabled={loading} onClick={handleSignIn}>{loading ?`Signing In` : `Sign in with Github`}</LoginButton>
      </LoginCard>
    </Container>
  )
}

const Container = styled.div`
  display: flex;
  flex-direction: column;
  align-items: center;
  height: 100vh;
`

const LoginCard = styled.div`
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  padding: 1rem;
  margin-top: 10rem;
`

const LoginHead = styled.p`
  font-size: 2rem;
  flex: 1;
  font-weight: bold;
`
const LoginButton = styled.button`
  height: 50px;
  width: 10rem;
  border: none;
  padding: 16px;
  cursor: pointer;
  transition: all 0.1s 0s ease-in-out;
  border-radius: 10px;
  &:hover {
    transform: scale(1.1);
    background: black;
    color: white;
  }
`
